[package]
name = "tg-searcher-index"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
html-escape = "0.2.14"
rand = "0.10.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
tantivy = { version = "0.26", default-features = false, features = ["mmap", "lz4-compression", "zstd-compression", "columnar-zstd-compression"] }
tantivy-analyzer-icu = { path = "../tantivy-analyzer-icu", features = ["tantivy-search"] }
thiserror = "2.0.19"
tokio = { version = "1.53.1", features = ["fs"] }
tracing = "0.1.44"

[dev-dependencies]
clap = { version = "4.6.4", features = ["derive"] }
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "test-util"] }
