use super::DEMO_SENTENCE;
use super::LONG_DOCUMENT_TEXT;
use super::{QueryTestCase, QueryTestGroup};

pub const GROUP: QueryTestGroup = QueryTestGroup {
    name: "Chinese Simple Query",
    docs: &[
        ("demo-1", DEMO_SENTENCE),
        ("zh-1", "我爱北京天安门"),
        ("zh-2", "北京是中国的首都"),
        ("zh-3", "今天天气真好"),
        ("zh-4", "苹果公司发布了新产品"),
        ("zh-5", "学习中文很有趣"),
        ("zh-6", "我"),
        ("zh-7", "北"),
        ("zh-8", "南京市长江大桥"),
        ("zh-9", "只有北字没有后面"),
        ("zh-10", "只有京字"),
        ("ja-1", "今日はいい天気です"),
        ("ja-2", "東京タワーは素晴らしい"),
        ("ja-6", "日本語を勉強しています"),
        ("ko-1", "안녕하세요"),
        ("en-1", "Hello World"),
        ("mix-5", "A我B"),
        ("mix-6", "あ我い"),
        ("norm-2", "㈱東京"),
        ("multi-1", "北京 在 东京"),
        ("multi-2", "北京，东京"),
        ("multi-3", "北京。东京"),
        ("multi-4", "京 东"),
        ("long-1", LONG_DOCUMENT_TEXT),
    ],
    cases: &[
        QueryTestCase {
            name: "single_han_zhong",
            query: "中",
            matches: &["long-1", "zh-2", "zh-5"],
            description: "Single Han char should match all docs containing it",
        },
        QueryTestCase {
            name: "single_han_wo",
            query: "我",
            matches: &["long-1", "mix-5", "mix-6", "zh-1", "zh-6"],
            description: "Single '我' should match all docs containing it",
        },
        QueryTestCase {
            name: "single_han_bei",
            query: "北",
            matches: &[
                "demo-1", "long-1", "multi-1", "multi-2", "multi-3", "zh-1", "zh-2", "zh-7", "zh-9",
            ],
            description: "Single '北' should match all docs containing it",
        },
        QueryTestCase {
            name: "single_han_reiwa",
            query: "令",
            matches: &["demo-1"],
            description: "Single '令' should match ㋿ doc via normalization",
        },
        QueryTestCase {
            name: "single_han_kabushiki",
            query: "株",
            matches: &["demo-1", "norm-2"],
            description: "Single '株' should match compatibility char docs",
        },
        QueryTestCase {
            name: "single_han_jing",
            query: "京",
            matches: &[
                "ja-2", "long-1", "multi-1", "multi-2", "multi-3", "multi-4", "norm-2", "zh-1",
                "zh-10", "zh-2", "zh-8",
            ],
            description: "Common char 京, matches multiple docs",
        },
        QueryTestCase {
            name: "single_han_ri",
            query: "日",
            matches: &["demo-1", "ja-1", "ja-6", "long-1"],
            description: "日 only in Japanese docs in our corpus",
        },
        QueryTestCase {
            name: "single_han_ben",
            query: "本",
            matches: &["ja-6", "long-1"],
            description: "本 in 日本語 (ja-6)",
        },
        QueryTestCase {
            name: "single_han_dong",
            query: "東",
            matches: &["ja-2", "long-1", "norm-2"],
            description: "東 in 東京タワー and ㈱東京",
        },
        QueryTestCase {
            name: "single_han_empty_result",
            query: "龘",
            matches: &[],
            description: "Rare char not in any doc",
        },
        QueryTestCase {
            name: "single_non_han_digit",
            query: "1",
            matches: &[],
            description: "[locked] single digit: ICU number tokens are whole, '1'≠'15'",
        },
        QueryTestCase {
            name: "route_single_han",
            query: "月",
            matches: &["demo-1"],
            description: "Single Han char → unigram only",
        },
        QueryTestCase {
            name: "multi_han_beijing",
            query: "北京",
            matches: &["long-1", "multi-1", "multi-2", "multi-3", "zh-1", "zh-2"],
            description: "'北京' should match docs containing 北京",
        },
        QueryTestCase {
            name: "multi_han_tianqi",
            query: "天气",
            matches: &["long-1", "zh-3"],
            description: "'天气' should match only the weather doc",
        },
        QueryTestCase {
            name: "reiwa_bigram",
            query: "令和",
            matches: &["demo-1"],
            description: "'令和' should match ㋿ doc",
        },
        QueryTestCase {
            name: "meiji_bigram",
            query: "明治",
            matches: &["demo-1"],
            description: "'明治' should match ㍾ doc",
        },
        QueryTestCase {
            name: "cross_expansion_bigram",
            query: "治株",
            matches: &["demo-1"],
            description: "Bigram spanning NFKC expansion boundary: 治 from ㍾, 株 from ㍿",
        },
        QueryTestCase {
            name: "beijing_not_partial",
            query: "北京",
            matches: &["long-1", "multi-1", "multi-2", "multi-3", "zh-1", "zh-2"],
            description: "Bigram query should not match docs with only one of the chars",
        },
        QueryTestCase {
            name: "tianqi_not_partial",
            query: "天气",
            matches: &["long-1", "zh-3"],
            description: "'天安门' contains '天' but not bigram '天气'",
        },
        QueryTestCase {
            name: "reiwa_not_partial",
            query: "令和",
            matches: &["demo-1"],
            description: "Unrelated docs should not match",
        },
        QueryTestCase {
            name: "no_prefix_match_cjk",
            query: "北京是",
            matches: &["long-1", "zh-2"],
            description: "北京是 bigrams (北京,京是) both in zh-2",
        },
        QueryTestCase {
            name: "punct_in_query_ignored",
            query: "北京。",
            matches: &["long-1", "multi-1", "multi-2", "multi-3", "zh-1", "zh-2"],
            description: "Punctuation in query is stripped by tokenizer",
        },
        QueryTestCase {
            name: "long_doc_hit",
            query: "北京",
            matches: &["long-1", "multi-1", "multi-2", "multi-3", "zh-1", "zh-2"],
            description: "Long doc containing 北京 is found",
        },
        QueryTestCase {
            name: "space_breaks_bigram_in_doc",
            query: "京东",
            matches: &[],
            description: "Doc '京 东' (space-separated) has no bigram '京东' — bigram query misses",
        },
        QueryTestCase {
            name: "cross_segment_bigram_no_match",
            query: "京东",
            matches: &[],
            description: "Continuous bigram query does not match docs with separated chars",
        },
        QueryTestCase {
            name: "zwsp_does_not_break_bigram",
            query: "京\u{200B}东",
            matches: &[],
            description: "ZWSP removed by NFKC, query acts as continuous bigram '京东'",
        },
        QueryTestCase {
            name: "each_segment_separate",
            query: "北京",
            matches: &["long-1", "multi-1", "multi-2", "multi-3", "zh-1", "zh-2"],
            description: "Each segment's bigrams exist independently",
        },
        QueryTestCase {
            name: "route_bigram_no_match",
            query: "二人",
            matches: &[],
            description: "二人 bigram not in index (二 and 人 are space-separated in doc)",
        },
    ],
};
