use super::DEMO_SENTENCE;
use super::{QueryTestCase, QueryTestGroup};

pub const GROUP: QueryTestGroup = QueryTestGroup {
    name: "Mixed Script Query",
    docs: &[
        ("demo-1", DEMO_SENTENCE),
        ("zh-1", "我爱北京天安门"),
        ("zh-2", "北京是中国的首都"),
        ("zh-6", "我"),
        ("ja-1", "今日はいい天気です"),
        ("ja-4", "食べる"),
        ("ja-11", "タベル"),
        ("ja-12", "たべる"),
        ("ko-1", "안녕하세요"),
        ("en-1", "Hello World"),
        ("en-2", "The quick brown fox"),
        ("en-3", "Machine learning is fun"),
        ("mix-1", "iPhone 15 Pro Max 发布"),
        ("mix-2", "COVID-19 疫情"),
        ("mix-3", "Hello 你好 World"),
        ("mix-4", "Python 3.12 版本发布"),
        ("mix-5", "A我B"),
        ("mix-6", "あ我い"),
        ("mix-7", "い안"),
        ("mix-8", "say い to you"),
        ("norm-4", "①②③"),
    ],
    cases: &[
        QueryTestCase {
            name: "iphone",
            query: "iPhone",
            matches: &["mix-1"],
            description: "English product name",
        },
        QueryTestCase {
            name: "mixed_a_wo_i",
            query: "我",
            matches: &["mix-5", "mix-6", "zh-1", "zh-6"],
            description: "Isolated Han (between kana) should match via unigram",
        },
        QueryTestCase {
            name: "hello_not_cjk",
            query: "hello",
            matches: &["en-1", "mix-3"],
            description: "English query should not match CJK docs",
        },
        QueryTestCase {
            name: "beijing_not_english",
            query: "北京",
            matches: &["zh-1", "zh-2"],
            description: "Chinese query should not match English docs",
        },
        QueryTestCase {
            name: "arabic_digits",
            query: "15",
            matches: &["mix-1"],
            description: "'15' matches 'iPhone 15', not '3.12' or '①②③'→'123'",
        },
        QueryTestCase {
            name: "han_kana_bigram_left",
            query: "あ我",
            matches: &["mix-6"],
            description: "Kana+Han bigram exists in mix-6; other 我 docs match via unigram fallback",
        },
        QueryTestCase {
            name: "han_kana_bigram_right",
            query: "我い",
            matches: &["mix-6"],
            description: "Han+Kana bigram exists in mix-6; other 我 docs match via unigram fallback",
        },
        QueryTestCase {
            name: "isolated_han_dropped_from_bigram",
            query: "A我",
            matches: &["mix-5", "mix-6", "zh-1", "zh-6"],
            description: "[locked] A我: 我 dropped in bigram, but unigram fallback matches 我-containing docs",
        },
        QueryTestCase {
            name: "hankana_mixed_bigram",
            query: "食べ",
            matches: &["ja-4"],
            description: "Han+Hiragana bigram precise match",
        },
        QueryTestCase {
            name: "kana_bigram_not_cross_hangul",
            query: "い안",
            matches: &["mix-7", "mix-8"],
            description: "No cross-group bigram; individual chars match as isolated unigrams",
        },
        QueryTestCase {
            name: "all_upper_cjk_mix",
            query: "HELLO 你好",
            matches: &["en-1", "mix-3"],
            description: "[locked] Uppercase+CJK: en-1 matches via 'hello', mix-3 via both terms",
        },
        QueryTestCase {
            name: "route_naive_shimokitazawa",
            query: "na\u{00EF}ve 下北沢",
            matches: &["demo-1"],
            description: "Per-token: naïve→diacritic, 下北沢→folded_bigram",
        },
        QueryTestCase {
            name: "route_number_han_mix",
            query: "8月",
            matches: &["demo-1"],
            description: "8 is non-CJK, 月 is Han → no bigram; 月 falls back to unigram",
        },
    ],
};
