use super::DEMO_SENTENCE;
use super::{QueryTestCase, QueryTestGroup};

pub const GROUP: QueryTestGroup = QueryTestGroup {
    name: "Semitic Script",
    docs: &[
        ("demo-1", DEMO_SENTENCE),
        ("ar-1", "احمد"),
        ("ar-2", "أحمد"),
        ("ar-3", "إبراهيم"),
        ("ar-4", "آمين"),
        ("ar-5", "الله"),
        ("ar-6", "الــــله"),
        ("ar-7", "كتاب"),
        ("ar-8", "كِتَابٌ"),
        ("ar-9", "مدرسة"),
        ("ar-10", "مدرسه"),
        ("ar-11", "فى"),
        ("ar-12", "في"),
        ("ar-13", "٢٠٢٤"),
        ("ar-14", "۲۰۲۴"),
        ("he-2", "שלום"),
        (
            "he-3",
            "\u{05D1}\u{05B0}\u{05BC}\u{05E8}\u{05B5}\u{05D0}\u{05E9}\u{05B4}\u{05C1}\u{05D9}\u{05EA}",
        ),
        ("he-4", "בראשית"),
    ],
    cases: &[
        QueryTestCase {
            name: "arabic_alif_hamza_above",
            query: "احمد",
            matches: &["ar-1", "ar-2"],
            description: "Alif hamza above (أ) normalized to plain alif",
        },
        QueryTestCase {
            name: "arabic_alif_hamza_below",
            query: "ابراهيم",
            matches: &["ar-3"],
            description: "Alif hamza below (إ) normalized to plain alif",
        },
        QueryTestCase {
            name: "arabic_alif_madda",
            query: "امين",
            matches: &["ar-4"],
            description: "Alif madda (آ) normalized to plain alif",
        },
        QueryTestCase {
            name: "arabic_harakat_plain_query",
            query: "كتاب",
            matches: &["ar-7", "ar-8"],
            description: "Plain query matches harakat doc: كِتَابٌ → كتاب",
        },
        QueryTestCase {
            name: "arabic_harakat_in_query",
            query: "كِتَابٌ",
            matches: &["ar-7", "ar-8"],
            description: "Harakat query matches plain doc: both fold to كتاب",
        },
        QueryTestCase {
            name: "arabic_harakat_still_stripped",
            query: "كتاب",
            matches: &["ar-7", "ar-8"],
            description: "Arabic harakat still stripped (by SemiticNorm, not DiacriticFolding)",
        },
        QueryTestCase {
            name: "arabic_tatweel_plain_query",
            query: "الله",
            matches: &["ar-5", "ar-6"],
            description: "Plain query matches tatweel doc: الــــله → الله",
        },
        QueryTestCase {
            name: "arabic_tatweel_in_query",
            query: "الــــله",
            matches: &["ar-5", "ar-6"],
            description: "Tatweel query matches both tatweel and plain docs",
        },
        QueryTestCase {
            name: "arabic_ta_marbuta",
            query: "مدرسه",
            matches: &["ar-10", "ar-9"],
            description: "Ta marbuta (ة) and ha (ه) unified",
        },
        QueryTestCase {
            name: "arabic_ta_marbuta_reverse",
            query: "مدرسة",
            matches: &["ar-10", "ar-9"],
            description: "Symmetric: ta marbuta query also matches ha doc",
        },
        QueryTestCase {
            name: "arabic_ya_maqsura",
            query: "في",
            matches: &["ar-11", "ar-12"],
            description: "Ya maqsura (ى) and ya (ي) unified",
        },
        QueryTestCase {
            name: "arabic_ya_maqsura_reverse",
            query: "فى",
            matches: &["ar-11", "ar-12"],
            description: "Symmetric: maqsura query matches ya doc",
        },
        QueryTestCase {
            name: "arabic_digits_ascii_query",
            query: "2024",
            matches: &["ar-13", "ar-14"],
            description: "ASCII query matches Arabic-Indic and Persian digit docs",
        },
        QueryTestCase {
            name: "arabic_digits_indic_query",
            query: "٢٠٢٤",
            matches: &["ar-13", "ar-14"],
            description: "Arabic-Indic digit query matches both digit forms",
        },
        QueryTestCase {
            name: "arabic_reverse_hamza",
            query: "أحمد",
            matches: &["ar-1", "ar-2"],
            description: "Hamza query matches both hamza and plain docs",
        },
        QueryTestCase {
            name: "hebrew_niqqud_stripped",
            query: "שלום",
            matches: &["demo-1", "he-2"],
            description: "Plain Hebrew matches niqqud doc: niqqud stripped by SemiticNorm",
        },
        QueryTestCase {
            name: "hebrew_niqqud_in_query",
            query: "\u{05E9}\u{05B8}\u{05C1}\u{05DC}\u{05D5}\u{05B9}\u{05DD}",
            matches: &["demo-1", "he-2"],
            description: "Niqqud in query matches plain doc: both fold to שלום",
        },
        QueryTestCase {
            name: "hebrew_bereshit",
            query: "בראשית",
            matches: &["he-3", "he-4"],
            description: "Plain בראשית matches niqqud version",
        },
    ],
};
