name: Bump version and upload to PyPI
on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  push_to_pypi:
    name: Push package to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Check version
        run: bash .github/workflows/check_version.sh

      - uses: pdm-project/setup-pdm@v3

      - name: Publish package distributions to PyPI
        run: pdm publish

